name: eventstateprocessor
description: A Flutter package that wrap flutter bloc package for clearer implementation
version: 1.1.0
homepage: https://github.com/extremevn/event_state_processor

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
